# Generated by Django 5.2.9 on 2025-12-28 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.IntegerField(help_text='Dose number (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of medicine per dose (tablets/ml/units)', max_digits=10)),
                ('time', models.TimeField(help_text='Time to take the dose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dose Schedule',
                'verbose_name_plural': 'Dose Schedules',
                'db_table': 'reminders_doseschedule',
                'ordering': ['reminder', 'dose_number'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('medicine_type', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('injection', 'Injection'), ('syrup', 'Syrup')], max_length=20)),
                ('dose_count_daily', models.IntegerField(help_text='Number of doses per day (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notification_methods', models.JSONField(default=list, help_text='List of notification methods: email, sms, push_notification')),
                ('start_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Current quantity of medicine', max_digits=10)),
                ('initial_quantity', models.DecimalField(decimal_places=2, help_text='Initial quantity when reminder was created', max_digits=10)),
                ('refill_reminder', models.BooleanField(default=False)),
                ('refill_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity threshold to trigger refill reminder', max_digits=10, null=True)),
                ('refill_reminder_sent', models.BooleanField(default=False, help_text='Flag to track if refill reminder has been sent')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'db_table': 'reminders_reminder',
                'ordering': ['-created_at'],
            },
        ),
    ]
