# Generated by Django 5.2.9 on 2025-12-28 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reminders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doseschedule',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_schedules', to='reminders.reminder'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user', 'is_active'], name='reminders_r_user_id_898b13_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['start_date'], name='reminders_r_start_d_6df954_idx'),
        ),
        migrations.AddIndex(
            model_name='doseschedule',
            index=models.Index(fields=['reminder', 'time'], name='reminders_d_reminde_6eead3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doseschedule',
            unique_together={('reminder', 'dose_number')},
        ),
    ]
