# Generated by Django 5.2.7 on 2025-12-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number with country code (e.g., +919876543210)', max_length=20, null=True),
        ),
    ]
