# Generated by Django 5.2.9 on 2025-12-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(db_index=True, max_length=255)),
                ('medicine_type', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('injection', 'Injection'), ('syrup', 'Syrup')], max_length=20)),
                ('current_quantity', models.DecimalField(decimal_places=2, help_text='Current stock quantity', max_digits=10)),
                ('unit', models.CharField(default='tablets', help_text='Unit of measurement (tablets, ml, units, etc.)', max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price', max_digits=10, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'db_table': 'inventory_inventory',
                'ordering': ['-created_at'],
            },
        ),
    ]
