# Generated by Django 5.2.9 on 2025-12-28 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reminder',
            field=models.ForeignKey(blank=True, help_text='Linked reminder for auto-management', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='reminders.reminder'),
        ),
    ]
