# Generated by Django 5.2.9 on 2025-12-28 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['user', 'medicine_name'], name='inventory_i_user_id_ddb454_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['user', 'is_active'], name='inventory_i_user_id_975473_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['expiry_date'], name='inventory_i_expiry__faeaca_idx'),
        ),
    ]
